name: Image Builder

on:
 push:
  branches:
   -main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    -name: Checkout repository
     uses: actions/checkout@v4
  
    -name: Image Builder
     run: docker build -t App .

